export { default as MainHome } from './MainHome';
export { default as HowItWorks } from './HowItWorks';
export { default as SupportedFaculties } from './SupportedFaculties';
export { default as Demo } from './Demo';
export { default as Pricing } from './Pricing';
export { default as FAQ } from './FAQ';
export { default as Contact } from './Contact';
export { default as Login } from './Login';
export { default as Register } from './Register';